name: CI

on:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3.1.0
      with:
        node-version: 16.13.2
    
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    
    - name: Instalação do Mocha e dos pacotes para teste
      run: |
        cd "DevOps Basico/Aula2/Codigo/aula-conversao-temperatura/src"
        npm install -g mocha
        npm install
        
    - name: Execução do teste
      run: mocha "DevOps Basico/Aula2/Codigo/aula-conversao-temperatura/src/test/convert.js"
